### ISSUE TITLE
Panic on keypress

### ISSUE THREAD

**Issue by vorner** [lotabout/skim#119]
Hello

I'm using sk to search through a largish file containing file names. When I press the first key (or, sometimes the second one), I get this panic:

```
stack backtrace:
thread '<unnamed>' panicked at 'index out of bounds: the len is 256 but the index is 344', libcore/unicode/bool_trie.rs:52:25                               
0:     0x563a34bc520f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h26bcec935f03ea20 at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
1:     0x563a34bd1d37 - std::sys_common::backtrace::print::h57677b80e795d1a7
at libstd/sys_common/backtrace.rs:71
at libstd/sys_common/backtrace.rs:59
2:     0x563a34bcab2f - std::panicking::default_hook::{{closure}}::hd17228a89fe0485a
at libstd/panicking.rs:211
3:     0x563a34bca894 - std::panicking::default_hook::h4fda70bd7c04cfe5
at libstd/panicking.rs:227
4:     0x563a34bcb20e - std::panicking::rust_panic_with_hook::h3d239545d3ada232
at libstd/panicking.rs:476
5:     0x563a34bcadb1 - std::panicking::continue_panic_fmt::haa7794da31560c90
at libstd/panicking.rs:390
6:     0x563a34bcac95 - rust_begin_unwind
at libstd/panicking.rs:325
7:     0x563a34c1073c - core::panicking::panic_fmt::hd2064739ab85a96f
at libcore/panicking.rs:77
8:     0x563a34c106f0 - core::panicking::panic_bounds_check::hc24fa7239813f86e
at libcore/panicking.rs:59
9:     0x563a34c102b0 - core::unicode::bool_trie::BoolTrie::lookup::h9376b9c8d13e6733
at libcore/unicode/bool_trie.rs:0
10:     0x563a34a841ec - skim::score::fuzzy_match::h61d37ee0c5680f6a
11:     0x563a34aa9339 - <skim::matcher::FuzzyEngine as skim::matcher::MatchEngine>::match_item::hbf877e672f41bed6
12:     0x563a34a9d273 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h3f7ecb80a7f6234e
13:     0x563a34aa40da - std::sys_common::backtrace::__rust_begin_short_backtrace::he318f789d84ca784
14:     0x563a34aca5b0 - std::panicking::try::do_call::h6852be1f2d65d96b
15:     0x563a34bdd2b9 - __rust_maybe_catch_panic
at libpanic_unwind/lib.rs:102
16:     0x563a34acdce5 - <F as alloc::boxed::FnBox<A>>::call_box::h608523cd1fc85e19
17:     0x563a34bc794d - std::sys_common::thread::start_thread::h59d14ae27c075453
at liballoc/boxed.rs:682
at libstd/sys_common/thread.rs:24
18:     0x563a34bba605 - std::sys::unix::thread::Thread::new::thread_start::h6aaf88e92c10158c
at libstd/sys/unix/thread.rs:90
19:     0x7f550dd683c2 - <unknown>
at /usr/src/debug/sys-libs/glibc-2.28-r4/glibc-2.28/nptl/pthread_create.c:486
20:     0x7f550dc742de - clone
at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I suspect some of the filenames aren't correct utf-8 and sk might balk at that?

However, the panic doesn't kill it (but it seems to make it useless, nothing more happens)

(It's the version publish on crates.io)

Any idea how to dig into it deeper or what might be happening?

**Comment by vorner** [comment]
A slightly better backtrace, with debug symbols, line numbers and some values.

```
[Current thread is 1 (Thread 0x7f96d27ca700 (LWP 3028))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f96d31f2545 in __GI_abort () at abort.c:79
#2  0x000055eea39aa4f7 in panic_abort::__rust_start_panic::abort () at src/libpanic_abort/lib.rs:51
#3  0x000055eea39aa4e6 in __rust_start_panic () at src/libpanic_abort/lib.rs:46
#4  0x000055eea39a32f9 in rust_panic () at src/libstd/panicking.rs:527
#5  0x000055eea39a32d2 in std::panicking::rust_panic_with_hook () at src/libstd/panicking.rs:498
#6  0x000055eea39a2d12 in std::panicking::continue_panic_fmt () at src/libstd/panicking.rs:385
#7  0x000055eea39a2bf6 in rust_begin_unwind () at src/libstd/panicking.rs:312
#8  0x000055eea39bafed in core::panicking::panic_fmt () at src/libcore/panicking.rs:85
#9  0x000055eea39bafa1 in core::panicking::panic_bounds_check () at src/libcore/panicking.rs:61
#10 0x000055eea39bef81 in core::unicode::bool_trie::BoolTrie::lookup () at src/libcore/unicode/bool_trie.rs:44
#11 0x000055eea349ca00 in core::char::methods::<impl char>::is_lowercase (self=1477600 '\x168be0')
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/libcore/char/methods.rs:602
#12 0x000055eea348e7a6 in skim::score::fuzzy_score (string=&[char](len: 44) = {...}, index=31, pattern=&[char](len: 1) = {...}, pattern_idx=0)
    at src/score.rs:43
#13 0x000055eea348eef8 in skim::score::fuzzy_match (choice=&[char](len: 44) = {...}, pattern=&[char](len: 1) = {...}) at src/score.rs:90
#14 0x000055eea3370eb8 in <skim::matcher::FuzzyEngine as skim::matcher::MatchEngine>::match_item (self=0x7f96bc001040, item=...) at src/matcher.rs:321
#15 0x000055eea33f99ad in skim::matcher::Matcher::run::{{closure}} (item=...) at src/matcher.rs:163
#16 0x000055eea3378f15 in <core::iter::FilterMap<I, F> as core::iter::iterator::Iterator>::next (self=0x7f96d27c9130)
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/libcore/iter/mod.rs:1672
#17 0x000055eea339d9cc in <alloc::vec::Vec<T>>::extend_desugared (self=0x7f96d27c91b0, iterator=...)
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/liballoc/vec.rs:1896
#18 0x000055eea33a51fd in <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend (self=0x7f96d27c91b0, iter=...)
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/liballoc/vec.rs:1793
#19 0x000055eea33a7985 in <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter (iterator=...)
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/liballoc/vec.rs:1788
#20 0x000055eea33a87f9 in <alloc::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter (iter=...)
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/liballoc/vec.rs:1688
#21 0x000055eea337511b in core::iter::iterator::Iterator::collect (self=...)
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/libcore/iter/iterator.rs:1468
#22 0x000055eea336fad1 in skim::matcher::Matcher::run (self=0x7f96d27c99b8, rx_item=...) at src/matcher.rs:163
#23 0x000055eea33b47a8 in skim::Skim::run_with::{{closure}} () at src/lib.rs:164
#24 0x000055eea33c0d52 in std::sys_common::backtrace::__rust_begin_short_backtrace (f=...)
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/libstd/sys_common/backtrace.rs:135
#25 0x000055eea3398e71 in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} ()
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/libstd/thread/mod.rs:469
#26 0x000055eea33a9101 in <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (self=..., _args=())
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/libstd/panic.rs:309
#27 0x000055eea3452f97 in std::panicking::try::do_call (data=0x7f96d27c9b80 "\002")
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/libstd/panicking.rs:297
#28 0x000055eea39aa4d9 in __rust_maybe_catch_panic () at src/libpanic_abort/lib.rs:30
#29 0x000055eea3452020 in std::panicking::try (f=...) at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/libstd/panicking.rs:276
#30 0x000055eea33a94f3 in std::panic::catch_unwind (f=...) at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/libstd/panic.rs:388
#31 0x000055eea3398af2 in std::thread::Builder::spawn_unchecked::{{closure}} ()
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/libstd/thread/mod.rs:468
#32 0x000055eea3399a5d in <F as alloc::boxed::FnBox<A>>::call_box (self=0x55eea50b8a60, args=())
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/liballoc/boxed.rs:734
#33 0x000055eea39a9e3e in _$LT$alloc..boxed..Box$LT$$LP$dyn$u20$alloc..boxed..FnBox$LT$A$C$$u20$Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h4074af23169dcda1 () at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/liballoc/boxed.rs:744
#34 std::sys_common::thread::start_thread () at src/libstd/sys_common/thread.rs:14
#35 std::sys::unix::thread::Thread::new::thread_start () at src/libstd/sys/unix/thread.rs:81
#36 0x00007f96d33c83c3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#37 0x00007f96d32d42df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) frame 11
#11 0x000055eea349ca00 in core::char::methods::<impl char>::is_lowercase (self=1477600 '\u{168be0}')
    at /rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/libcore/char/methods.rs:602
602	/rustc/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/libcore/char/methods.rs: No such file or directory.
(gdb) locals
Undefined command: "locals".  Try "help".
(gdb) info locals
c = 1477600 '\u{168be0}'
c = 0x7f96d27c80c4 "\x168be0\070\xe00049cc\xc400168b\x96d27c80\177\000\000\xa348e7a6\x55een\000\000\000\000\000\000n\030\xeea339a2U\000\000\xbc05c180n\000\000\000\xd27c85e8\x7f96\\\x96ac66de\177\000\000\r\xeea3399eU\000\000,\000\000\000"
(gdb) up
#12 0x000055eea348e7a6 in skim::score::fuzzy_score (string=&[char](len: 44) = {...}, index=31, pattern=&[char](len: 1) = {...}, pattern_idx=0)
    at src/score.rs:43
43	    if prev.is_lowercase() && cur.is_uppercase() {
(gdb) info locals
prev = 1477600 '\u{168be0}'
cur = 110 'n'
pattern_char = 110 'n'
score = -1
```

**Comment by lotabout** [comment]
@vorner Thanks for the report. I'll check when I got time.
Besides, it is possible to share the original input? Besides the local variables shown in the stacktrace, the original input would help to understand how it got here.

**Comment by vorner** [comment]
Sorry, I don't want to share this ono. But I'm willing to run whatever experiments on it, or I might try to create one with similar characteristics if need be.

**Comment by lotabout** [comment]
@vorner If possible, could you please compile the branch: https://github.com/lotabout/skim/tree/ticket-119 and test?

A previous commit change `from_utf8_lossy` to `from_utf8_unchecked` trying to avoid some overhead on checking utf8 character. Seems it brings much troubles.

**Comment by vorner** [comment]
Yes, thank you, this has fixed it for me.

**Comment by lotabout** [comment]
Close this by https://github.com/lotabout/skim/pull/120
