### ISSUE TITLE
sk 0.10.4 panics on macOS

### ISSUE THREAD

**Issue by baggiponte** [lotabout/skim#550]
When I run `sk` on my M3 Mac I get this error:

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Custom { kind: Other, error: TerminfoEntryNotFound })', src/lib.rs:319:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The backtraces:

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Custom { kind: Other, error: TerminfoEntryNotFound })', src/lib.rs:319:14
stack backtrace:
   0:        0x10040befc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h782e083efa4700b5
   1:        0x1002e79c8 - core::fmt::write::hdcd44492977669f9
   2:        0x1003fb1e0 - std::io::Write::write_fmt::h7f32f27b72970ad5
   3:        0x10040bc44 - std::sys_common::backtrace::print::h6868989d298a5d93
   4:        0x1003fbcb8 - std::panicking::default_hook::{{closure}}::he58f0ab435f26824
   5:        0x1003fb984 - std::panicking::default_hook::h0f0ccb5a1a0c4466
   6:        0x1003fc5b8 - std::panicking::rust_panic_with_hook::hf392a622566eb9b6
   7:        0x10040c548 - std::panicking::begin_panic_handler::{{closure}}::h07b7cf65243520e5
   8:        0x10040c4bc - std::sys_common::backtrace::__rust_end_short_backtrace::h4972088065ba8a0d
   9:        0x1003fc1b4 - _rust_begin_unwind
  10:        0x10042d95c - core::panicking::panic_fmt::hc67fbbe16e2d8abd
  11:        0x10042d928 - core::result::unwrap_failed::had2324ff96cef11b
  12:        0x10029ecc0 - sk::real_main::hb5cede4e0ac1696c
  13:        0x1002932d8 - sk::main::h23d0744db0777fb3
  14:        0x10036c7bc - std::sys_common::backtrace::__rust_begin_short_backtrace::hb18954e03a3161ac
  15:        0x1002a0358 - _main
```

Is it looking for a `.terminfo` folder or something like that? How can I improve this bug report? Thanks!

**Comment by LoricAndre** [comment]
Is it still the case with the latest versions ?

**Comment by baggiponte** [comment]
Doesn't seem so! Thanks for bumping.
